travel/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user
from .forms import LoginForm, RegisterForm
from .models import User
from . import db

# create a blueprint
bp = Blueprint('auth', __name__)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if(login_form.validate_on_submit() == True):
        # get the username and password from the database
        user_name = login_form.username.data
        password = login_form.password.data
        u1 = User.query.filter_by(name=user_name).first()
        # if there is no user with that name
        if u1 is None:
            error = 'Incorrect user name'
        # check the password - notice password hash function
        # takes the hash and password
        elif not check_password_hash(u1.password_hash, password):
            error = 'Incorrect password'
        if error is None:
            # all good, set the login_user of flask_login to manage the user
            login_user(u1)
            return redirect(url_for('main.home'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')


@bp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    # the validation of form submis is fine
    if (register.validate_on_submit() == True):
        # get username, password and email from the form
        uname = register.username.data
        pwd = register.password.data
        email = register.email.data
          # check if a user exists
        u1 = User.query.filter_by(name=uname).first()
        if u1:
            flash('User name already exists, please login')
            return redirect(url_for('auth.login'))
            # don't store the password - create password hash
        pwd_hash = generate_password_hash(pwd)
            # create a new user model object
        new_user = User(name=uname, password_hash=pwd_hash, emailid=email)
        db.session.add(new_user)
        db.session.commit()
            # commit to the database and redirect to HTML page
        return redirect(url_for('main.home'))
    # the else is called when there is a get message
    else:
        return render_template('user.html', form=register, heading='Register')

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return 'You have been logged out'

travel/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from .models import Destination

mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def home():
    return render_template('index.html')
    # if 'email' in session and session['email'] is not None:
    #     # print(session['email'])
    #     message = "<h1>Hello " + session['email'] + "</h1>"
    # else:
    #     message = '<h1>HELLO</h1>'
    # return message

def index():
    destinations = Destination.query.all()
    return render_template('index.html', destinations=destinations)

# route to allow users to search
@mainbp.route('/search')
def search():
    # get the search string from request
    if request.args['search']:
        dest = "%" + request.args['search'] + '%'
# use filter and like function to search for matching destinations
        destinations = Destination.query.filter(Destination.name.like(dest)).all()
# render index.html with few destinations
        return render_template('index.html', destinations=destinations)
    else:
        return redirect(url_for('main.home'))


@mainbp.route('/logout')
def logout():
    if 'email' in session:
        session.pop('email', None)
    return 'Session has been cleared'

travel/templates/base.html
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Travel App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>

<body>
    <!-- Header -->
    <header class="bg-light border-bottom">

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">

                <!-- Your Travel App Name or Logo -->
                <a href="/" class="navbar-brand">
                    My Travel App
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar -->
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link" href="#">Destinations</a>
                        <a class="nav-item nav-link" href="#">Bookings</a>
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link disabled text-muted" href="#"><span>Welcome, {{ current_user.name
                                }}</span></a>
                        <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                        {% endif %}
                    </div>
                </div>

            </div>
        </nav>

        {% block header %}
        {% endblock %}

    </header>

    {% block content %}
    {% endblock %}

    <footer class="footer">
        <div class="text-center py-2 bg-light">
            <span class="text-dark">Copyright &copy; 2021</span>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
</body>

</html>

travel/templates/index.html
{% extends 'base.html' %}

{% block header %}
    <!--Jumbotron-->
      <div class="container">
         <div class="row justify-content-center mt-5 pb-4">
            <div class="col-md-8">
               <div class="card shadow p-5 mb-5 bg-light">
                  <h1 class="text-center mb-3">Find our best travel deals</h1>
                  <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}" >
                  <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                  <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Submit</button>
                  </form>
               </div>
            </div>
         </div>
      </div>
 {% endblock %}

 {% block content %}
    <div class="container">
         <!-- justified in the center, margin top and bottom and the column contains a 10 grid -->
        <div class="row mt-5 mb-5 justify-content-center">
          <div class="col-md-10">
            <div class="media border p-3">
              <img class="align-self-center mr-3" style="max-width: 120px" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Earth_Western_Hemisphere_transparent_background.png/600px-Earth_Western_Hemisphere_transparent_background.png" alt="Planet Earth">
              <div class="align-self-center media-body">
                <h5 class="mt-0">Find the best destinations on earth</h5>
                <p class="d-none d-sm-block">Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.</p>
                <a href="#" class="btn btn-primary">Join Now</a>
              </div>
            </div>
          </div>
        </div>
    
        {% if destinations %}
        <div class="row justify-content-center">
        {% for destination in destinations %}
          <div class="card mb-5 mr-5 px-0 col-md-3">
            <img class="card-img-top" height="200rem" src="{{destination.image}}" alt="{{destination.name}}">
            <div class="card-body">
              <h5 class="card-title">{{destination.name}}</h5>
              <p class="card-text">{{destination.description}}</p>
              <a href="{{url_for('destination.show', id=destination.id)}}" class="btn btn-danger">View Details</a>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
          </div>
          {% endfor %}
          </div>
          
          {% endif %}
        </div>

      </div>
     {% endblock %}

travel/templates/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</head>

<body>

    <div class="container col-md-6">
        <h2>Login Form</h2>
        <!--update the action and the method with relevant information-->
        <form action="" , method="POST">
            <!-- keeps the label and text in a group vertically stacked-->
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
            </div>

            <div class="form-group">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
            </div>

            <div class="form-group">
                <label for="phone">Phone:</label>
                <input type="text" class="form-control" id="phone" placeholder="Enter phone" name="phone">
            </div>

            <button type="submit" class="btn btn-default">Submit</button>

        </form>
    </div>

</body>

</html>

travel/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container-fluid page-header">
    <h4>{{heading}}</h4>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}
<!-- check if there are any messages -->
<div class="container-fluid">
    <div class="row mt-3 mb-3">
        <div class="col-md-12">
            {% for message in messages %}
            <!--loop through the messages-->
            <div class="alert alert-info">{{ message }}</div>
            <!--display as alert-->
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
{% endwith %}

    <!-- Form rendering is simple and easy if using bootstrap -->
    <div class="col-md-6 ml-5">
        {{wtf.quick_form(form)}}
    </div>

    <!-- When you have login form, then do show the user a link to register -->
    {% if heading|lower =='login' %}
    <div class="col-md-4 mb-5 ml-5">
        <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
    </div>
    {% endif %}
</div>
{% endblock %}